---
# tasks file for ansible-role-nsd
- name: Fix https://.launchpad.net/ubuntu/+source/nsd/+bug/1311886
  user: name=nsd home=/var/lib/nsd shell=/bin/false system=yes createhome=no

- name: Install NSD name server
  apt: name=nsd update_cache=yes cache_valid_time=3600 state=latest

- name: Create SSL keys and certificates
  command: nsd-control-setup creates=/etc/nsd/nsd_control.pem
  when: nsd_remote_control_enable == "yes" and ((ansible_distribution=='Ubuntu' and {{ ansible_distribution_version | version_compare('14.04', '>=') }}) or (ansible_distribution=='Debian' and {{ ansible_distribution_version | version_compare('8', '>=') }}))
  notify:
   - restart nsd

- name: Create config file
  template: src=nsd.conf.j2 dest=/etc/nsd/nsd.conf owner=root group=root mode=0644 validate='nsd-checkconf %s'
  when: (ansible_distribution=='Ubuntu' and {{ ansible_distribution_version | version_compare('14.04', '>=') }}) or (ansible_distribution=='Debian' and {{ ansible_distribution_version | version_compare('8', '>=') }})
  notify:
   - restart nsd

- name: Create config file
  template: src=nsd.conf.j2 dest=/etc/nsd3/nsd.conf owner=root group=root mode=0644 validate='nsd-checkconf %s'
  when: (ansible_distribution=='Ubuntu' and {{ ansible_distribution_version | version_compare('14.04', '<') }}) or (ansible_distribution=='Debian' and {{ ansible_distribution_version | version_compare('8', '<') }})
  notify:
   - restart nsd

- name: Enable NSD on boot and start it
  service: name=nsd state=started enabled=yes

- name: Setup ufw firewall rule
  ufw: rule=allow port={{ nsd_port }}
  when: nsd_setup_ufw
