---
# tasks file for ansible-role-nsd
- name: Fix https://.launchpad.net/ubuntu/+source/nsd/+bug/1311886
  user: name=nsd home=/var/lib/nsd shell=/bin/false system=yes createhome=no

- name: Install NSD name server
  apt: name=nsd update_cache=yes cache_valid_time=3600 state=latest

- name: Create SSL keys and certificates
  command: /usr/sbin/nsd-control-setup creates=/etc/nsd/nsd_control.pem
  notify:
   - restart nsd

- name: Create config file
  template: src=nsd.conf.j2 dest=/etc/nsd/nsd.conf owner=root group=root mode=0644 validate='nsd-checkconf %s'
  notify:
   - restart nsd

- name: Enable NSD on boot and start it
  service: name=nsd state=started enabled=yes

- name: Setup ufw firewall rule
  ufw: rule=allow port={{ nsd_port }}
  when: nsd_setup_ufw
